helm: fix argocd hanging [1.11] (#6790)
* helm: fix argocd hanging (#6759)

* helm jobs: increase ttl values and check for crds

* make ttl configurable

* cl

* Adding changelog file to new location

* Deleting changelog file from old location

* update text

Co-authored-by: changelog-bot <changelog-bot>

* change to FIX for backport so changelog bot will stop complaining

diff --git a/install/helm/gloo/templates/5-resource-migration-job.yaml b/install/helm/gloo/templates/5-resource-migration-job.yaml
--- a/install/helm/gloo/templates/5-resource-migration-job.yaml
+++ b/install/helm/gloo/templates/5-resource-migration-job.yaml
@@ -35,6 +35,11 @@ spec:
           - /bin/sh
           - -c
           - |
+            if ! kubectl get crd upstreams.gloo.solo.io; then
+              echo "Could not find Upstream CRD. Gloo Edge may not be installed yet. Skipping migration job."
+              exit 0
+            fi
+
             # remove existing helm labels/annotations since the custom resources are no longer managed by helm.
             # also add resource-policy to tell helm not to delete the resource during upgrade.
             # select by label app=gloo, which is on all CRs from the gloo helm chart.
@@ -44,7 +49,7 @@ spec:
             kubectl annotate --overwrite gateways.gateway.solo.io -n {{ $.Release.Namespace }} -l app=gloo helm.sh/hook- helm.sh/hook-weight- meta.helm.sh/release-name- meta.helm.sh/release-namespace- helm.sh/resource-policy=keep || exit $?
             kubectl label gateways.gateway.solo.io -n {{ $.Release.Namespace }} -l app=gloo,app.kubernetes.io/managed-by=Helm app.kubernetes.io/managed-by- || exit $?
       restartPolicy: OnFailure
-  ttlSecondsAfterFinished: 0
+  ttlSecondsAfterFinished: {{ .Values.gateway.rolloutJob.ttlSecondsAfterFinished }}
 {{- if .Values.global.glooRbac.create }}
 ---
 apiVersion: v1
@@ -95,6 +100,42 @@ metadata:
 roleRef:
   kind: Role
   name: gloo-resource-migration
+  apiGroup: rbac.authorization.k8s.io
+subjects:
+- kind: ServiceAccount
+  name: gloo-resource-migration
+  namespace: {{ .Release.Namespace }}
+---
+kind: ClusterRole
+apiVersion: rbac.authorization.k8s.io/v1
+metadata:
+  name: gloo-resource-migration{{ include "gloo.rbacNameSuffix" . }}
+  labels:
+    app: gloo
+    gloo: rbac
+  annotations:
+    "helm.sh/hook": pre-upgrade
+    "helm.sh/hook-weight": "0" # must be created before job
+    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
+rules:
+- apiGroups: ["apiextensions.k8s.io"]
+  resources: ["customresourcedefinitions"]
+  verbs: ["get", "list"]
+---
+kind: ClusterRoleBinding
+apiVersion: rbac.authorization.k8s.io/v1
+metadata:
+  name: gloo-resource-migration{{ include "gloo.rbacNameSuffix" . }}
+  labels:
+    app: gloo
+    gloo: rbac
+  annotations:
+    "helm.sh/hook": pre-upgrade
+    "helm.sh/hook-weight": "0" # must be created before job
+    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
+roleRef:
+  kind: ClusterRole
+  name: gloo-resource-migration{{ include "gloo.rbacNameSuffix" . }}
   apiGroup: rbac.authorization.k8s.io
 subjects:
 - kind: ServiceAccount
