fix: custom readiness probe with custom healthCheck path not working (#5464)
* fix: custom readiness probe with custom healthCheck path not working

* Use PR instead of main

* Adding argocd tests

* Adding changelog

* fix build-and-publish-script

* Revert "Use PR instead of main"

This reverts commit 1e2ca56ba387d28af6e7fd89ed0e944f9921dc62.

* bump gloo

diff --git a/install/helm/gloo-ee/templates/71-resource-rollout-check-job.yaml b/install/helm/gloo-ee/templates/71-resource-rollout-check-job.yaml
--- a/install/helm/gloo-ee/templates/71-resource-rollout-check-job.yaml
+++ b/install/helm/gloo-ee/templates/71-resource-rollout-check-job.yaml
@@ -9,15 +9,12 @@ metadata:
   labels:
     app: gloo
     gloo: resource-rollout
-  name: gloo-ee-resource-rollout
+  name: gloo-ee-resource-rollout-check
   namespace: {{ .Release.Namespace }}
   annotations:
-    # Argo checks the status of resources in an app to determine its state. Since a job is cleaned up (deleted) after ttlSecondsAfterFinished,
-    # the missing job causes the argo app to go out of sync.
-    # Annotating this job as a Sync hook along with an argo-specific hook deletion policy ensures that even when the job is cleaned up,
-    # it does not alter the state of the argo app and that it is still in sync.
-    argocd.argoproj.io/hook: Sync
-    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
+    "helm.sh/hook": post-install,post-upgrade
+    "helm.sh/hook-weight": "3" # run this before the oss resource rollout check job
+    {{- include "gloo.jobHelmDeletePolicySucceededAndBeforeCreation" .Values.gloo.gateway.rolloutJob | nindent 4 }}
 spec:
   {{- include "gloo.jobSpecStandardFields" .Values.gloo.gateway.rolloutJob | nindent 2 -}}
   template:
@@ -75,16 +72,39 @@ spec:
           - /bin/sh
           - -c
           - |
-            {{ if and .Values.gloo.gateway.enabled .Values.gloo.gateway.validation.enabled .Values.gloo.gateway.validation.webhook.enabled -}}
-            # if validation webhook is enabled, wait for deployment rollout so validation service will be available
-            kubectl rollout status deployment -n {{ .Release.Namespace }} gloo
-            {{- end }}
-
-            # apply Gloo Edge Enterprise custom resources
+            # Check if Gloo Edge applied custom resources
             if [ $HAS_CUSTOM_RESOURCES == "true" ]
             then
-              kubectl apply -f /etc/gloo-custom-resources/custom-resources || exit $?
+              # Wait for the enterprise resource rollout job to complete
+              kubectl -n {{ .Release.Namespace }} get job gloo-ee-resource-rollout &> /dev/null
+              if [ $? -eq 0 ]
+              then
+                # Exit immediately if the enterprise rollout job failed
+                kubectl -n {{ .Release.Namespace }} get job gloo-ee-resource-rollout -o jsonpath='{.status.conditions[?(@.type=="Failed")].status}' | grep -i "True" &> /dev/null
+                if [ $? -eq 0 ]
+                then
+                    echo "Enterprise rollout job failed"
+                    exit 1
+                fi
+                echo "Waiting for the enterprise resource rollout job to complete"
+                kubectl -n {{ .Release.Namespace }} wait --for=condition=complete job gloo-ee-resource-rollout --timeout={{ .Values.gloo.gateway.rolloutJob.timeout }}s || exit 1
+              fi
+
+              # If the resource has been applied, re-applying it should output something like this
+              # gateway.gateway.solo.io/default unchanged
+              # If not it will output
+              # gateway.gateway.solo.io/default configured
+              # gateway.gateway.solo.io/default created
+              # This indicates that the resource was not applied in the resource rollout job
+              FAILED_RESOURCES=$(kubectl apply -f /etc/gloo-custom-resources/custom-resources | grep -iv ' unchanged')
+              if [ ! -z "$FAILED_RESOURCES" ]
+              then
+                echo "The following resources failed to be applied in the resource rollout job $FAILED_RESOURCES"
+                exit 1
+              else
+                echo "The resource rollout job successfully applied all the resources"
+              fi
             else
-              echo "no custom resources to apply"
+              echo "no custom resources to check"
             fi
 {{- end }}{{/* if .Values.gloo.gateway.rolloutJob.enabled  */}}
