1.16.x out of space fix (#5776)
* Out of space fix

* Update fix-build-v2-merge.yaml

diff --git a/.github/workflows/composite-actions/prep-go-runner/action.yaml b/.github/workflows/composite-actions/prep-go-runner/action.yaml
--- a/.github/workflows/composite-actions/prep-go-runner/action.yaml
+++ b/.github/workflows/composite-actions/prep-go-runner/action.yaml
@@ -26,19 +26,43 @@ runs:
       run: |
         echo "Before clearing disk space:"
         df -h
+        docker system df -v
         
-        # https://github.com/actions/virtual-environments/issues/709
-        sudo apt-get clean
-        
+        echo "Removing large packages"
+        sudo apt-get remove -y '^dotnet-.*'
+        sudo apt-get remove -y '^llvm-.*'
+        sudo apt-get remove -y 'php.*'
+        sudo apt-get remove -y '^mongodb-.*'
+        sudo apt-get remove -y '^mysql-.*'
+        sudo apt-get remove -y azure-cli google-chrome-stable firefox powershell mono-devel libgl1-mesa-dri
+        sudo apt-get autoremove -y
+        sudo apt-get clean -y
+
         # Clean up pre-installed tools
-        # https://github.com/actions/virtual-environments/issues/1918
-        sudo rm -rf /usr/share/dotnet
-        sudo rm -rf /opt/ghc
-        sudo rm -rf /usr/local/share/boost
-        sudo rm -rf $AGENT_TOOLSDIRECTORY
-        
+        sudo rm -rf /usr/local/lib/android || true
+        sudo rm -rf /usr/share/dotnet || true
+        sudo rm -rf /usr/local/graalvm || true
+        sudo rm -rf /opt/ghc || true
+        sudo rm -rf /usr/local/.ghcup || true
+        sudo rm -rf /usr/local/share/boost || true
+        sudo rm -rf /usr/local/share/powershell || true
+        sudo rm -rf /usr/local/share/chromium || true
+        sudo rm -rf $AGENT_TOOLSDIRECTORY || true
+
+        # Clean up images
+        docker image rm node:16 || true
+        docker image rm node:16-alpine || true
+        docker image rm node:18 || true
+        docker image rm node:18-alpine || true
+        docker image rm node:20 || true
+        docker image rm node:20-alpine || true
+        # remove the dangling images and containers
+        docker images | tail -n +2 | awk '$1 == "<none>" {print $3}' | xargs --no-run-if-empty docker rmi
+        docker ps -a | tail -n +2 | awk '$2 ~ "^[0-9a-f]+$" {print $1}' | xargs --no-run-if-empty docker rm --volumes=true
+
         echo "After clearing disk space:"
         df -h
+        docker system df -v
     - name: Configure git for private modules
       shell: bash
       run: git config --global url."https://${{ inputs.github-token }}@github.com/solo-io/".insteadOf "https://github.com/solo-io/"
