[1.16] add || true to apt shenanigans (#5814)

diff --git a/.github/workflows/composite-actions/prep-go-runner/action.yaml b/.github/workflows/composite-actions/prep-go-runner/action.yaml
--- a/.github/workflows/composite-actions/prep-go-runner/action.yaml
+++ b/.github/workflows/composite-actions/prep-go-runner/action.yaml
@@ -27,16 +27,17 @@ runs:
         echo "Before clearing disk space:"
         df -h
         docker system df -v
-        
+
+        # https://github.com/actions/runner-images/discussions/3242 github runners are bad at cleanup
         echo "Removing large packages"
-        sudo apt-get remove -y '^dotnet-.*'
-        sudo apt-get remove -y '^llvm-.*'
-        sudo apt-get remove -y 'php.*'
-        sudo apt-get remove -y '^mongodb-.*'
-        sudo apt-get remove -y '^mysql-.*'
-        sudo apt-get remove -y azure-cli google-chrome-stable firefox powershell mono-devel libgl1-mesa-dri
-        sudo apt-get autoremove -y
-        sudo apt-get clean -y
+        sudo apt-get remove -y '^dotnet-.*' || true
+        sudo apt-get remove -y '^llvm-.*' || true
+        sudo apt-get remove -y 'php.*' || true
+        sudo apt-get remove -y '^mongodb-.*' || true
+        sudo apt-get remove -y '^mysql-.*' || true
+        sudo apt-get remove -y azure-cli google-chrome-stable firefox powershell mono-devel libgl1-mesa-dri || true
+        sudo apt-get autoremove -y || true
+        sudo apt-get clean -y || true
 
         # Clean up pre-installed tools
         sudo rm -rf /usr/local/lib/android || true
